info:
  name: '@project.name@'
  version: '@project.version@'
  description: '@project.description@'

server:
  port: 8080

# --------------------------------------------
# Profile Configuration
# --------------------------------------------
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5488/postgres
    username: root
    password: admin
  liquibase:
    change-log: classpath:/db/changelog/changeLog-master.xml
    enabled: true