INSERT INTO public.city_list VALUES (1, 'Tokyo','Tokyo_url');
INSERT INTO public.city_list VALUES (2, 'Jakarta','Jakarta_url');
INSERT INTO public.city_list VALUES (3, 'Mumbai','Mumbai_url');
INSERT INTO public.city_list VALUES (4, 'Manila','Manila_url');
INSERT INTO public.city_list VALUES (5, 'Shanghai','Shanghai_url');
INSERT INTO public.city_list VALUES (6, 'São Paulo','SãoPaulo_url');
INSERT INTO public.city_list VALUES (7, 'Seoul','Seoul_url');
INSERT INTO public.city_list VALUES (8, 'Mexico City','MexicoCity_url');
INSERT INTO public.city_list VALUES (9, 'Guangzhou','Guangzhou_url');
INSERT INTO public.city_list VALUES (10, 'Beijing','Beijing_url');
INSERT INTO public.city_list VALUES (11, 'Cairo','Cairo_url');